### ISSUE TITLE
Issues with rclone options on cloud upload

### ISSUE THREAD

**Issue by davidjameshowell** [madslundt/docker-cloud-media-scripts#1]
I just recently built this out and was having issues with the upload portion. I investigated what the command was using to upload and noticed that many of the options were drawn from the variables file. A lot of these options are not present inside of the rclone copy command and would fail the upload as a result of them missing (despite not indicating as such).

For reference, the upload with the configurable options: https://github.com/madslundt/docker-cloud-media-scripts/blob/master/scripts/cloudupload.script#L43

And the variables reference: https://github.com/madslundt/docker-cloud-media-scripts/blob/master/scripts/variables#L10

It was enough for me to duplicate the rclone_config into an upload variable (although duplicate parameters, but to allow for future flexibility in options).

**Comment by madslundt** [comment]
Thank you very much for the feedback. I'll make sure to fix this right away!

**Comment by madslundt** [comment]
I just pushed changes so copy/move does not use --read-only --allow-non-empty --allow-other --max-read-ahead

Again thanks for the heads up!
