### ISSUE TITLE
Question about default configuration

### ISSUE THREAD

**Issue by Antexa** [madslundt/docker-cloud-media-scripts#10]
First of all thank you for your work. 

I noticed that with the default configurations, I could not launch a movie by viewing it from its half.

What type of setting should I choose (chunks, buffer, ...) if I am looking to view large files (~ 25GB)

Hardware Spec :
Processor: Intel Xeon E3-1225v2 - (4c/4t)
Frequency: 3.2GHz / 3.6GHz
RAM: 16GB DDR3 1333MHz
Discs: 2x2To SATA
Bandwidth: 250 Mbps

**Comment by madslundt** [comment]
If your internet connection is 250 Mbps you can increase **CHUNK_SIZE**, **MAX_READ_AHEAD** and **BUFFER_SIZE**. However you should still be able to watch a movie with the default settings
What happened when you launch the movie?

**Comment by Antexa** [comment]
SOrry didn't notice you answer me... 

I get stuck from the begin of a film, i'm started to think the cloud-media docker stack could be the problem, but after days, i think it's related to Plex himself... I need to reboot it to access to the media again. 

Transcode problem ? don't think so, maybe the acess to the local decrypt, i notice that happen only with newly media.

**Comment by madslundt** [comment]
Did you find out what the problem was?

**Comment by Antexa** [comment]
No, with your default settings I get stuck when I launch movies, I try the second settings you recommend. 

Still investigate to understand the behavior. 

My current compose settings : 
`  cloud-media:
    restart: unless-stopped
    image: madslundt/cloud-media-scripts
    container_name: cloud-media
    environment:
      #- READ_ONLY=1
      #- BUFFER_SIZE=16 
      #- CHUNK_SIZE=5
      - CLEAR_CHUNK_MAX_SIZE=1000G
      - REMOVE_LOCAL_FILES_WHEN_SPACE_EXCEEDS_GB=2000
      - FREEUP_ATLEAST_GB=1000
      - PGID=1000
      - PUID=1000
    volumes:
      - /home/user/resource/local-media:/local-media:shared
      - /home/user/resource/local-decrypt:/local-decrypt:shared
      - /home/user/resource/cloud-encrypt:/cloud-encrypt:shared
      - /home/user/resource/cloud-decrypt:/cloud-decrypt:shared
      - /home/user/resource/chunks:/chunks
      - /home/user/docker/cloud-media-scripts/config:/config
      - /home/user/docker/cloud-media-scripts/log:/log
    privileged: true
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices: 
      - /dev/fuse:/dev/fuse`

`/dev/md4        3.6T  456G  3.0T  14% /home
local-crypt:    1.0P     0  1.0P   0% /home/user/resource/cloud-decrypt
unionfs         1.1P  1.1P  3.0T 100% /home/user/resource/local-media`

With these current settings, I didn't get stuck when I try to launch a movie, and plex working well.

**Comment by madslundt** [comment]
Your settings shouldn't have any impact on streaming movies. What you settings do is that instead of caching your media for 24h it will cache up to 1000GB media. That should not have any effect when streaming.

Unless you had  `BUFFER_SIZE=16` and `CHUNK_SIZE=5` before, I can see that it can give problems due to the low values. However, that is not included in the default settings. The default value for these settings are `BUFFER_SIZE=500M` and `CHUNK_SIZE=10M`
