### ISSUE TITLE
Symlinks seem to point to wrong dir?

### ISSUE THREAD

**Issue by Dulanic** [madslundt/docker-cloud-media-scripts#11]
So I am going crazy and don't know where the problem lies... to make my life easy I do ln -s /local-media/Media/Shows to /tv and the same /w Movies. Movies looks fine, but yet Shows doesn't? 

If I mount the encrypted version to /test it looks fine...

EX: sudo rclone mount --buffer-size 500M --checkers 16 --allow-non-empty --allow-other gd-decrypt:/Media /test &

Looks fine /w /Media/Shows/ShowName and /Media/Movies/MovieNames

Then I do this.... and it mounts to /tv/Shows? That makes no sense...
sudo ln -s /local-media/Media/Shows /tv    
yet the /Movies version looks fine?
sudo ln -s /local-media/Media/Movies /movies
 The layout is the same, the manually mounted dirs look fine, but the symlinks look off for /local-media?

**Comment by Dulanic** [comment]
Ignore my stupidity, you're docker rocks :)

**Comment by madslundt** [comment]
Nps :)

Glad you like it
