### ISSUE TITLE
Enhancement: Script change - Add verbosity options for logging

### ISSUE THREAD

**Issue by Dulanic** [madslundt/docker-cloud-media-scripts#15]
I have a request to add a verbose option to the docker containers. I'd like to have the ability to see more output for troubleshooting etc.  I think this could also apply to rmlocal since that involves the move?

My idea is:

- Add a env variable for log_verbose or something along that name I'd think.
- Make current behavior default 
- Add -v=x option to $rclone_options based on above env variable.
- Example update, not positive if coded properly. https://github.com/madslundt/docker-cloud-media-scripts/compare/master...Dulanic:master

**Comment by madslundt** [comment]
Right now there you can add -v to add verbose to the rclone command.

But I'll definitely look into having more verbose.

**Comment by Dulanic** [comment]
Thanks. My main idea was mostly around logging but think it's close to correct if it's not.
