### ISSUE TITLE
Data loading to /local-media on hard drive?

### ISSUE THREAD

**Issue by Dulanic** [madslundt/docker-cloud-media-scripts#18]
So I've been running this for 5 days and suddenly I noticed my sda drive is full. I couldn't figure it out until I stopped the docker and noticed there was still 135GB in local-media? I ran a rclone move and it removed them all because they all existed on the cloud? Seems odd why this happened?

Now that I looked at some of this, most of these look like items I thought I deleted? Is it maybe downloading it back down to the local dir if I delete it from local-media?

```
me@me:/local-media$ sudo du -d 2 -h
48M     ./Media/Books
2.2G    ./Media/Shows
104G    ./Media/Movies
106G    ./Media
106G    .
```

**Comment by madslundt** [comment]
How does your docker command look like?

**Comment by Dulanic** [comment]
`docker create --name cloud --restart=always -v /local-media:/local-media:shared 	v /local-decrypt:/local-decrypt:shared -v /docker/containers/cloud/config:/config -v /downloads/plexdrive​:/chunks -v /logs:/log -e CLEAR_CHUNK_MAX_SIZE="1000G" -e REMOVE_LOCAL_FILES_WHEN_SPACE_EXCEEDS_GB="1000" -e FREEUP_ATLEAST_GB="500" -e PUID=1000 -e PGID=1000 --privileged --cap-add=MKNOD --cap-add=SYS_ADMIN --device=/dev/fuse  madslundt/cloud-media-scripts`

**Comment by madslundt** [comment]
Has this problem reoccured?
