### ISSUE TITLE
Use this with docker-compose?

### ISSUE THREAD

**Issue by zjpleau** [madslundt/docker-cloud-media-scripts#19]
I would like to use add this to my docker-compose.yml along the rest of my applications however I am unsure how to translate this line into the format:

--privileged --cap-add=MKNOD --cap-add=SYS_ADMIN --device=/dev/fuse \

Any idea?

Thanks!

**Comment by madslundt** [comment]
I've not tried it with docker compose, but you should be able to use it like this in your yaml file:
```
services:
...
  cloud-media-scripts:
    ...
    privileged: true
    -cap-add: "MKNOD"
    cap-add: "SYS_ADMIN" 
    device: "/dev/fuse"
```

I'm not sure if the quotes are correct though.

**Comment by zjpleau** [comment]
Thanks! After that advice plus some experimenting, this is the syntax for my docker-compose.yml file that I found to work:

   privileged: true
   devices:
     - /dev/fuse
   cap_add:
     - MKNOD
     - SYS_ADMIN

**Comment by madslundt** [comment]
Glad to hear that you worked it out!

I'll add it to the documentation

**Comment by zjpleau** [comment]
I noticed one strange thing when assembling this with docker-compose. For some reason when running _docker exec cloud-media-scripts check_ I get the following error message:

`docker exec cloud-media-scripts check


Missing colon (:) in RCLONE_CLOUD_ENDPOINT ("gdrive:")
Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup
`

This also happens when running rmlocal.

The synax in my .yml _should_ be correct:
`
     - ENCRYPT_MEDIA=0
     - RCLONE_CLOUD_ENDPOINT="gdrive:"`

Without the " " around gdrive: it errors out immediately, and the colon is definitely present.

This works fine when I test without docker-compose. Still troubleshooting--just thought it was interesting.
