### ISSUE TITLE
Issue removing file on media folder

### ISSUE THREAD

**Issue by bounty1342** [madslundt/docker-cloud-media-scripts#22]
Hi there,

Removing a file with the 'rm' command dosen't seems to work.
If the contener restart, the rm file will show up again.

Also from time to time, it will dowload to the local folder a file already in the cloud (Gdrive), any idea why ?

Regards,
Bounty1342

**Comment by madslundt** [comment]
Are you removing a file from /local-media?
If you are, and the file is uploaded to cloud, it can not be removed. If you want to remove an uploaded file, you have to use `rclone delete` command

**Comment by bounty1342** [comment]
For the files that gets downloaded several time, it very obvious for the nfo files. And as there is a lot of them, it's very annoying. Will try to remove the Metadata in sonnar.

Concerning the issue removing the file. It was in fact pretty stupid.
Was doing a rm command on the media folder, but the cloud's were read only...

I switched them to RW with the env. variable, and wa able to rclone delete and rm the file.

Thanks, you can close it :)


(pebkac )
