### ISSUE TITLE
Slow upload due to existing files

### ISSUE THREAD

**Issue by alxdc9** [madslundt/docker-cloud-media-scripts#24]
The cloudupload script takes a lot of time to execute even if there are no new files to upload. This is mainly due to the rclone copy call on each file. If the files already exists on the remote target, it will still require from 3 to 10 secondes (per file !) to check it. With my (no so large) library with 1200 files, it already requires more than 3 hours to simply list and check if files already exist.

Wouldn't it make sense to first compare files from /cloud-decrypt and /local-decrypt and only upload those who only exist locally ? I guess comparing file name and size should be enough to define if a file is different. What do you think ?

**Comment by madslundt** [comment]
Actually a very good idea. I've added a quick way to only copy the ones that are not in the /cloud-decrypt.

**Comment by alxdc9** [comment]
Excellent! Scipt is now executed in less than 10 seconds if all files already uploaded.

**Comment by madslundt** [comment]
Great! And thanks!

**Comment by alxdc9** [comment]
It seems that you only upload if the file does not exist on the remote. But if a local file has changed, it won't be uploaded. Would be possible to compare the modification dates to define if upload is required ?
