### ISSUE TITLE
Missing colon (:) in RCLONE_CLOUD_ENDPOINT ("gd-crypt:") error with docker-compose

### ISSUE THREAD

**Issue by jgaurilo** [madslundt/docker-cloud-media-scripts#25]
When RCLONE_CLOUD_ENDPOINT is defined in docker-compose.yml, cloudupload and check scripts give following error:

Missing colon (:) in RCLONE_CLOUD_ENDPOINT ("gd-crypt:")
Run: docker exec -ti <DOCKER_CONTAINER> rclone_setup

When RCLONE_CLOUD_ENDPOINT is not defined (and using default name gd-crypt when setting up rclone) it works without problems.

I'm using cloud-media-scripts without encryption but I assume this happens also when using encryption.

I also saw this on another issue #19

Here are my configs:

docker-compose.yml
>   cloud-media-scripts:
    image: madslundt/cloud-media-scripts
    restart: always
    container_name: cloud-media-scripts
    volumes:
      - /opt/gdrive:/local-media:shared
      - /opt/appdata/cloud-media-scripts/external/media:/local-decrypt:shared
      - /opt/appdata/cloud-media-scripts/config:/config
      - /opt/appdata/cloud-media-scripts/external/plexdrive:/chunks
      - /opt/appdata/cloud-media-scripts/data/db:/data/db
      - /opt/appdata/cloud-media-scripts/logs:/log
      - /opt/appdata/cloud-media-scripts/external/cloud-encrypt:/cloud-encrypt:shared
      - /opt/appdata/cloud-media-scripts/external/cloud-decrypt:/cloud-decrypt:shared
    environment:
      - ENCRYPT_MEDIA=0
      - RCLONE_CLOUD_ENDPOINT="gd-crypt:"
      - PGID=998
      - PUID=999
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - mknod
      - sys_admin

rclone.conf
> [gd-crypt]
type = drive
client_id =
client_secret =
token = {"access_token":"snip"

Versions:

> Operating System: Debian GNU/Linux 9 (stretch)
Kernel: Linux 4.9.0-4-amd64
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
latest image from docker hub

**Comment by madslundt** [comment]
Hi there.

Sorry for the late answer.

I've tried your docker-compose.yml and got the same error. It happened because it was not stripped for quotes, so the variable RCLONE_CLOUD_ENDPOINT was not having a colon at the end. I've send out a fix to strip them for quotes (" and ')
