### ISSUE TITLE
Cloud-decrypt : Input/output error

### ISSUE THREAD

**Issue by bounty1342** [madslundt/docker-cloud-media-scripts#28]
Hi,

When I do a ls on the cloud-decrypt file, it gives an error message:
![ll cloud-decrypt](https://user-images.githubusercontent.com/6307253/35201027-cb4db536-ff17-11e7-8834-7dfa89d7b1c3.PNG)

Strange thing is that when doing a rclone lsd on the drive, the folder are there :
![rclone lsd gd-crypt](https://user-images.githubusercontent.com/6307253/35201028-cb642136-ff17-11e7-992a-6e41a4c63842.PNG)

Any idea how to give more information do help debug it ?

**Comment by madslundt** [comment]
Did you configure rclone correctly? gd-crypt looks like to be the endpoint to Drive.
cloud-decrypt uses rclone crypt type. You can view an example of an rclone.conf [over here](https://github.com/madslundt/cloud-media-scripts/blob/master/rclone/rclone.template.conf)

**Comment by bounty1342** [comment]
My sanitised version of rclone.conf :

[gd]
type = drive
client_id = xxxxxx.apps.googleusercontent.com
client_secret = xxxxxx
token = {"access_token":"xxxxxx","token_type":"Bearer","refresh_token":"xxxxxx","expiry":"2018-01-22T01:48:50.78353922Z"}

[gd-crypt]
type = crypt
remote = gd:Save
filename_encryption = standard
password = xxxxxx
password2 = xxxxxx

[local-crypt]
type = crypt
remote = /cloud-encrypt/Save
filename_encryption = standard
password = xxxxxx
password2 = xxxxxx

It was working fine, but suddently wasn't able to list the files anymore ! The guilty part is certainly the expiry date of the token !

Maybe an idea of improvement, to at list warn users about it :)

Keep up the good work, thanks for looking into this.
