### ISSUE TITLE
Issue mounting local-crypt

### ISSUE THREAD

**Issue by bounty1342** [madslundt/docker-cloud-media-scripts#29]
Hi,

Think there is a issue with the last rclone :
```
[ 2018-01-31@00:59:28 ] Mounting Google Drive mountpoint: /cloud-encrypt
[ 2018-01-31@00:59:33 ] Mounting decrypted Google Drive: /cloud-decrypt
2018/01/31 00:59:33 NOTICE: Encrypted drive 'local-crypt:': poll-interval is not supported by this remote
[ 2018-01-31@00:59:38 ] Mounting union: /local-media
```

I connected to the container with `docker exec -ti <DOCKER_CONTAINER> bash`
Then i tried the following command :
`rclone --config /config/rclone.conf lsd local-crypt:`
![image](https://user-images.githubusercontent.com/6307253/35600221-2ef58fb6-062d-11e8-93f6-98980f9dcaff.png)
So far, this is the expected behavior.

But when I run a  `ll cloud-decrypt/`, it results in :
![image](https://user-images.githubusercontent.com/6307253/35600239-4bbefe7a-062d-11e8-889d-7b235ae27a98.png)

Could this poll-interval option be refusing the mount ?
How can i debug further ?

Regards,
Bounty1342

**Comment by bounty1342** [comment]
Moving back to release 1.2.3 works fine.

I open a question on the rclone forum :
https://forum.rclone.org/t/folder-not-showned-input-output-error/4708

I do think it's related to moving from 1.3.7 to 1.3.9.

Regards,
Bounty1342

**Comment by madslundt** [comment]
Indeed it looks related to rclone 1.3.9.
I'll dig deeper and try get an understanding what goes wrong and I'll follow your question on rclone fourm.

Thanks.

**Comment by bounty1342** [comment]
@madslundt : Is there a way to activate more logs on the mounting part of rclone ? 
I reproduce the same issue with a fresh install.

`$ docker exec 9aa check
ls: reading directory '/cloud-decrypt': Input/output error

Waiting for /cloud-encrypt
`

**Comment by bounty1342** [comment]
@madslundt, issue was with the '.' folder. After suppressing or renaming it and then remounting, it went fine 😍 

Spent so much time on this... And it's so stupid... Right in the error message 🤣

**Comment by bounty1342** [comment]
https://github.com/ncw/rclone/issues/2135
