### ISSUE TITLE
More verbose output of rclone for uploads

### ISSUE THREAD

**Issue by davidjameshowell** [madslundt/docker-cloud-media-scripts#3]
I believe it would be much more beneficial to capture more verbose output of `rclone copy` in order to verify that files are uploaded and retrieve more introspection into those uploads. Currently, if uploads are interrupted or error, there is nothing to indicate as such (beyond maybe corrupted files) as the notification to the cloudupload.log is transmitted before rclone copy even begins (part of the original issue I encountered).

**Comment by madslundt** [comment]
I've added the option to passthrough the arguments given for the scripts to rclone. For example if you run `docker exec <DOCKER_CONTAINER> cloudupload -v` **-v** is given to the rclone command.

https://github.com/madslundt/docker-cloud-media-scripts#commands
