### ISSUE TITLE
:shared not visible on host nor other containers

### ISSUE THREAD

**Issue by cere84** [madslundt/docker-cloud-media-scripts#33]
Hi there,

I have been trying to set up everything up on Docker for Synology and all seems ok but I am unable to see any files in local-media nor any other shared (I can see files created inside config and logs) from file station or another container with ubuntu.

The config I used to create the container is:

docker create \
--name cloud-media-scripts \
-v /volume1/dockersconfig/gdrive/local-media:/local-media:shared \
-v /volume1/dockersconfig/gdrive/local-decrypt:/local-decrypt:shared \
-v /volume1/dockersconfig/gdrive/cloud-encrypt:/cloud-encrypt:shared \
-v /volume1/dockersconfig/gdrive/cloud-decrypt:/cloud-decrypt:shared\
-v /volume1/dockersconfig/gdrive/config:/config \
-v /volume1/dockersconfig/gdrive/chunks:/chunks \
-v /volume1/dockersconfig/gdrive/logs:/log \
-e CLEAR_CHUNK_MAX_SIZE="1000G" \
-e REMOVE_LOCAL_FILES_WHEN_SPACE_EXCEEDS_GB="2000" \
-e FREEUP_ATLEAST_GB="1000" \
--privileged --cap-add=MKNOD --cap-add=SYS_ADMIN --device=/dev/fuse \
madslundt/cloud-media-scripts

And I can see from logs that everything is mounted with no errors and files can be seen in the container.
Do you know if I am doing something wrong with the creation commands?

Regards

**Comment by bounty1342** [comment]
Are you sure you don't have another container whitout the share :flag ?

**Comment by cere84** [comment]
Yes, I think the problem is with permissions of the user daemon within DSM (Synology).
If I try to start the container manually I get the following message:

root@NAS:/volume1# docker start plexcloud
Error response from daemon: linux mounts: Path /volume1/mnt is mounted on /volume1 but it is not a shared mount.
Error: failed to start containers: plexcloud

I’ve tried to use the root folder /mint/ and it works straight away but is not ideal due to limited space and not visible on DSM.

**Comment by R91g** [comment]
Do you tried using -e PGID _Group id_ and -e PUID _User id_?

**Comment by cere84** [comment]
@R91g I have just tried with same results. 
I am about to give up, Plexdrive and Rclone work on DSM directly but I'd love to have it in Docker (on Ubuntu Server had no problems)

**Comment by freakshock88** [comment]
I tried for hours to get this working on my Synology, but I finnaly found something which made it work.

Before creating the docker container (with the :shared appends), run this on your synology:

`sudo mount --make-shared /volume1` (or whatever your volume is).
After that create the docker container like described in the Readme, and everything works :)
