### ISSUE TITLE
Can't start container with mount  :shared is causing issues

### ISSUE THREAD

**Issue by inject00r** [madslundt/docker-cloud-media-scripts#35]
Hi all,

after updating my qnap it seems that using :shared property is causing a problem.

When I remove it I can only use the local content (as intended), when I add it I am not able to start the container.

Error response from daemon: linux mounts: Path /share/Media/cloud-encrypt is mounted on /share/CACHEDEV1_DATA but it is not a shared mount.

I can access the folders through /share/Media or through /share/CACHEDEV1_DATA which seems to be linked.

I tried through console something like "mount --make-shared /share/CACHEDEV1_DATA" but I only get an error.

Does anybody has an idea how to mount this share or to solve this problem in general? Normally I would say I even don't need CACHEDEV1_DATA since it worked before without...

Thank you. :-)

**Comment by inject00r** [comment]
I created a new folder and bound it to my original settings:

> mkdir /plexdrive
> mount --bind /share/Media /plexdrive

Now I am getting the same problem with different folder
`Error response from daemon: linux mounts: Path /plexdrive/cloud-decrypt is mounted on /plexdrive but it is not a shared mount.`

Does anybody mean what it means with is not a shared mount? I am trying now for hours changing settings in the docker container and within the shell. :-(

**Comment by madslundt** [comment]
Hi there.

Can you give some details about the docker version you are using?

Also does it work if you don't bind /share/Media/cloud-encrypt but just ignore it when creating the container?

**Comment by inject00r** [comment]
It does not help. After I removed the cloud-encrypt entry it takes the next volume which is used. First it showed encrypt as problem, no it shows decrypt which is not shared.

It seems that it might be a docker bug regarding a default setting of MountFlags=slave when docker is started through systemd.

https://groups.google.com/forum/#!topic/portworx/A2vtTjjzSLI

Here are the settings:

`Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   fd7dc00
 Built:        Thu Feb  8 15:57:38 2018
 OS/Arch:      linux/amd64

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   fd7dc00
 Built:        Thu Feb  8 15:57:38 2018
 OS/Arch:      linux/amd64
 Experimental: false        `

**Comment by madslundt** [comment]
Did you try to unset MountFlags=slave and restart Docker?

**Comment by inject00r** [comment]
Do you have an idea where I can do this on QNAP? Can't find it. :-((((((

**Comment by madslundt** [comment]
I don't own a QNAP but I think you'll have to SSH into it and run the command `unset MountFlags=slave`

**Comment by madslundt** [comment]
Did that help?

**Comment by inject00r** [comment]
Thanks for the link and asking for it! Really appreciate it! Unfortunately not since systemctl is not available. Question is how this can be and how I could set since no path of the example is available. But when I try the check to see if I am affected I am positive.

**Comment by inject00r** [comment]
Is it possible to edit a bind volume entry as shared via portainer? Just tried to start the container there. Same problem but as expected. Pressed recreate to pull the latest build and deploy with same settings. It automatically starts the container. works. But the problem is - even though I set in the past :shared it does not reuse this information and instead it sets it automatically to :rprivate. Really strange.

**Comment by freakshock88** [comment]
I tried for hours to get this working on my Synology, but I finnaly found something which made it work.

Before creating the docker container (with the :shared appends), run this on your synology:

`sudo mount --make-shared /volume1` (or whatever your volume is).
After that create the docker container like described in the Readme, and everything works :)

**Comment by madslundt** [comment]
> I tried for hours to get this working on my Synology, but I finnaly found something which made it work.
> 
> Before creating the docker container (with the :shared appends), run this on your synology:
> 
> `sudo mount --make-shared /volume1` (or whatever your volume is).
> After that create the docker container like described in the Readme, and everything works :)

Thank you! I've added it to the readme
