### ISSUE TITLE
Everything seems okay but folders stay empty.

### ISSUE THREAD

**Issue by freakshock88** [madslundt/docker-cloud-media-scripts#36]
I set up everything accordings to the docs on my Synology using Docker.
When I run the check command it returns "Everything looks good".
The only thing I can get to work is an encrypted google drive upload, when I put files in the local-decrypt folder and manually start the upload. Other folders stay completely empty. Also no logs are in my /logs folder.

Here's my docker command:

```
docker create \

--name cloud-media-scripts \

-v /docker/plexcloud/logs:/logs \

-v /docker/plexcloud/data/db:/data/db \

-v /docker/plexcloud/config:/config \

-v /HDD1/PlexCloud/local-media:/local-media:shared \

-v /HDD1/PlexCloud/local-decrypt:/local-decrypt:shared \

-v /HDD1/PlexCloud/cloud-encrypt:/cloud-encrypt \

-v /HDD1/PlexCloud/cloud-decrypt:/cloud-decrypt:shared \

-v /HDD1/PlexCloud/chunks:/chunks \

--privileged --cap-add=MKNOD --cap-add=SYS_ADMIN --device=/dev/fuse \

madslundt/cloud-media-scripts
```

So these three folders stay empty:
```
- /HDD1/PlexCloud/local-media

- /HDD1/PlexCloud/cloud-encrypt

- /HDD1/PlexCloud/cloud-decrypt
```
Any idea what's going wrong here?

**Comment by madslundt** [comment]
Sorry for the late answer.

If you go into the docker container are all the folders also empty in there?

**Comment by alexyao2015** [comment]
You need to wait for plexdrive to build it's cache. Try waiting overnight. Plexdrive should be set to -v 3 or -v 2 to limit confusion.
