### ISSUE TITLE
Not uploading

### ISSUE THREAD

**Issue by zjpleau** [madslundt/docker-cloud-media-scripts#8]
I passed through the variable:
`-e REMOVE_LOCAL_FILES_WHEN_SPACE_EXCEEDS_GB="200" \`
but I'm sitting at 400+GB and no uploading has taken place yet.

When I run "docker logs cloud-media-scripts -f", I see this:
`[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Executing mongod --logpath /log/mongod.log
Executing mount
2017-09-08T18:27:56.858+0000 I CONTROL  [main] log file "/log/mongod.log" exists; moved to "/log/mongod.log.2017-09-08T18-27-56".
[ 2017-09-08@18:28:01 ] Mounting Google Drive mountpoint: /cloud-decrypt
[ 2017-09-08@18:28:06 ] Mounting union: /local-media
`
Seems  hung at "Mounting union" but the union appears to work fine. 

Any ideas? Running the currently posted commit but I've been removing/re-adding your commits for the past week or so. Thanks!

**Comment by madslundt** [comment]
Are you running `docker exec <CLOUD_CONTAINER> rmlocal` or `docker exec <CLOUD_CONTAINER> cloudupload`?

That container does not upload by it self, but need you to execute a command to either move all you have to the cloud (that means it gets deleted afterwards from your local disk) or copy the data to the cloud

**Comment by zjpleau** [comment]
Oh I see, I guess for some reason I thought it was monitoring the space used and running the script when it hit the quota. Running the rmlocal script now--thanks.

What about the container logs showing stuck at "Mounting union"? I know it used to constantly check if the mounts were valid. Do you see this too or is it possibly something on my end? I tried a full reboot just in case there was a problem with the mount on the host-end.

**Comment by madslundt** [comment]
It isn't stuck. It just don't write any more after mounting union :) I'll add a finish log so it doesn't confuse people.
